project:
  type: website
  output-dir: C:\Users\akeal66.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Abbey Kealey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: Projects.qmd
        text: Projects
    

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
editor: visual

